import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getClient } from '../lib/sanity.server'

const frontpageQuery = `
  {
    "siteSettings": *[_id == "siteSettings"][0] {
      ...
    }
  }
`

export async function getStaticProps({ preview = false }) {
  const data = await getClient(preview).fetch(frontpageQuery)
  return {
    props: { data, preview },
  }
}

const Home: NextPage = ({ data }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {data.siteSettings?.label?.en}
        </h1>

        <p className={styles.description}>{data.siteSettings?.description?.en}</p>
        <p>
          Data from Sanity
        </p>
      </main>
    </div>
  )
}

export default Home
